# -*- coding: utf-8 -*-
"""Google street view.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrC0pTzBXJinTzCcAM-5akw7mcWDa0gf
"""

!pip install reverse_geocoder

import reverse_geocoder as rg
import pprint

def reverseGeocode(coordinates):
    result = rg.search(coordinates)
    pprint.pprint(result)

if __name__=="main_":
     coordinates =(22.547664103739855, 88.35977031044695) #hard coded coordinates
     reverseGeocode(coordinates)

import requests
#import result

api_key = "api_key"
url = "https://maps.googleapis.com/maps/api/staticmap?"
center ="Kolkata" #set as per preference
zoom = 10 #set zoom level
r = requests.get(url + "center =" + center + "&zoom =" +
                   str(zoom) + "&size = 400x400&key =" +
                             api_key + "sensor = false") 
f = open('image.png', 'wb') #generates png  
f.write(r.content)
f.close()